### PR TITLE
Fix for older titanium projects

### PR DESCRIPTION
**Pull request by svickers**
Building to device was not working for older titanium projects because the module was missing armv6 binary.  
https://wiki.appcelerator.org/display/guides/iOS+Module+Development+Guide#iOSModuleDevelopmentGuide-

### CODE REVIEW

**Comment by dhcustom** [comment]
Sweet. But before I merge, could you explain what the two added files are? I don't think they are necessary to be in the repo. They seem to be generated files when building the module.

**Comment by svickers** [comment]
Sorry, those were included by accident.  Can you exclude them from the pull or does the entire changeset get moved over?  Still learning git :)

**Comment by dhcustom** [comment]
I cannot just pull certain files from a commit. Can you add to this commit? If not you can close the pull request and create a new one. I would suggest adding those files to the .gitignore file so someone else won't make the same mistake. I'm new to this as well. :)

**Comment by jonatansberg** [comment]
@svickers You should be able to make additional commit(s) to the branch from which this pull request was made to correct your accidental adds. Those commits will then appear here allowing @dhcustom to pull your fix and close the request.

**Pull request closed without merging**
